### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Crispy-Cream**
- Updating README.md to provide a sneak peek at what buttons will look like.
 - Updating js/index.js and fixing guild-related problems. As well as combining https://github.com/GmBodhi/shandler/pull/8 :)

Should be 100% done soon.

### CODE REVIEW

**Comment by GmBodhi** [comment]
Can you delete the changes for the js files? Cuz I've already fixed the issues.

**Comment by Crispy-Cream** [comment]
All fixed as well as updated the buttons

**Comment by GmBodhi** [comment]
I'm assuming there is no difference from the original code Can I merge?

**Comment by Crispy-Cream** [comment]
> I'm assuming there is no difference from the original code. Can I merge?

In the index.js there are just some like ";" added but nothing really else and the readme was updated and the interaction.js was fixed with the variables

**Pull request merged**
